name: CI-template

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      docker_arguments:
        required: false
        type: string
    secrets:
      aws-access-key-id:
        description: "access key id for ecr"
        required: true
      aws-secret-access-key:
        description: "secret access key for ecr"
        required: true
      helm-repo-access-key:
        description: "clone into devops repo"
        required: true

jobs:
  changes:
    runs-on: ubuntu-18.04
    outputs:
      services: ${{ steps.build_list.outputs.service_build_list }}
    env:
      gitSha: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set branch-name
        id: branch-name
        run: |
          echo "BRANCH_NAME=$(echo $GITHUB_REF_NAME | sed "s/[^a-zA-Z0-9]/-/g")" >> $GITHUB_ENV
          echo "::set-output name=branch::${{ env.BRANCH_NAME }}"  
      - name: get changed files (not pr)
        id: changed-files
        run: |
          changed_files=$(git diff --name-only `git merge-base origin/develop HEAD`)
          while IFS= read -r changed_file ; do 
            echo "changed_file: $changed_file"
            all_changed_files=$all_changed_files",$changed_file"
          done <<< "$changed_files"
          all_changed_files="${all_changed_files:1}"
          echo "all_changed_files: $all_changed_files"
          echo "::set-output name=all_changed_files::$all_changed_files"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: 'cypator/devops'
          path: devops
          token: ${{ secrets.helm-repo-access-key }}
          ref: develop  
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: create package list
        id: build_list
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          pip install checksumdir
          # python devops/scripts/get-service-build-list.py
          python .github/workflows/scripts/get-service-build-list.py
          service_build_list=$(cat $GITHUB_WORKSPACE/service_build_list.json | jq -r .)
          echo "service_build_list: $service_build_list"
          echo "::set-output name=service_build_list::$service_build_list"

  docker-build:
    runs-on: ubuntu-20.04
    needs: [changes]
    if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
    timeout-minutes: 45
    strategy:
      matrix:
        service-list: ${{ fromJson(needs.changes.outputs.services) }}
    env:
      REPOSITORY_NAME: ${{ matrix.service-list }}
    steps:
      - name: Get the output time
        run: echo "The step output ${{ toJson(matrix.service-list) }}"
      
      - name: printing repository name
        run: echo $REPOSITORY_NAME

  