name: Deploy
on:
  workflow_call:
    secrets:
      aws-access-key-id:
        description: "access key id for ecr"
        required: true
      aws-secret-access-key:
        description: "secret access key for ecr"
        required: true
      helm-repo-access-key:
        description: "clone into devops repo"
        required: true
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        description: Environment to deploy to
        default: develop
        required: true
        options:
          - develop
      confirm-env:
        type: string
        description: Confirm the environment to deploy
        required: true
        default: develop
jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: github.event.inputs.target-env == github.event.inputs.confirm-env
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1
      - name: download zip file artifact from s3
        run: |
          command=$(aws s3 cp s3://cypatorbackend/*-feature-check-ci.zip deploy.zip)
          echo "s3 command: $command"
          pwd
          ls -la
      - name: create secrets
        id: create-secrets
        run: |
          #download secret from AWS
          echo "env: $TARGET_ENV"
          SECRETS="secret-$TARGET_ENV.yaml"
          secret_arn=$(aws secretsmanager list-secrets --query "SecretList[?Tags[?Key=='deployment' && Value=='develop']]" | jq -r '.[0].ARN')
          echo $(aws secretsmanager get-secret-value --secret-id $secret_arn | jq -r '.SecretString') > $SECRETS_FILE_PATH
          pwd
          ls -la
          cat values-secrets-raw.json
        env:
          TARGET_ENV: ${{ github.event.inputs.target-env }}
          SECRETS_FILE_PATH: ./values-secrets-raw.json
   
