name: Deploy
on:
  workflow_call:
    secrets:
      aws-access-key-id:
        description: "access key id for ecr"
        required: true
      aws-secret-access-key:
        description: "secret access key for ecr"
        required: true
      helm-repo-access-key:
        description: "clone into devops repo"
        required: true
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        description: Environment to deploy to
        default: develop
        required: true
        options:
          - develop
      confirm-env:
        type: string
        description: Confirm the environment to deploy
        required: true
        default: develop
jobs:
  validate-image:
    runs-on: ubuntu-20.04
    if: github.event.inputs.target-env == github.event.inputs.confirm-env
    outputs:
      valid_image: ${{ steps.check-image.outputs.image_exist }}
    steps:
      - name: cloning to helm repo
        uses: actions/checkout@v3
        with:
          repository: cypator/devops
          token: ${{ secrets.helm-repo-access-key }}
          path: helm
          fetch-depth: 0
          ref: main
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1
      - name: set branch-name
        run: |
          echo "BRANCH_NAME=$(echo $GITHUB_REF_NAME | sed "s/[^a-zA-Z0-9]/-/g")" >> $GITHUB_ENV
      - name: check if image exists for the branch name
        uses: actions/checkout@v2
        id: check-image
        run: |
          sh .github/workflows/scripts/deploy-image.sh